#!/usr/bin/env python
# -*- coding: utf-8 -*-


import scrapy
from scrapy.crawler import CrawlerProcess
from stocker.spiders.stocksph import StocksphSpider


def main():
    print "Crawling in my skin..."
    process = CrawlerProcess()

    process.crawl(StocksphSpider)
    process.start()



if __name__ == '__main__':
    main()
